meta:
  environment: redis-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: redis
    networks:
      - name: redis1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: redis1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.28.0/30
    reserved:
    - 10.244.28.1
    static:
    - 10.244.28.2

  - cloud_properties:
      name: random
    range: 10.244.28.4/30
    reserved:
    - 10.244.28.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.28.8/30
    reserved:
    - 10.244.28.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.28.12/30
    reserved:
    - 10.244.28.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.28.16/30
    reserved:
    - 10.244.28.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.28.20/30
    reserved:
    - 10.244.28.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.28.24/30
    reserved:
    - 10.244.28.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.28.28/30
    reserved:
    - 10.244.28.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.28.32/30
    reserved:
    - 10.244.28.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.28.36/30
    reserved:
    - 10.244.28.37
    static: []
