meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: redis-master
    templates:
    - name: redis
      release: redis
    - name: sentinel
      release: redis
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( merge ))
    properties:
      sentinel:
        masters:
           - 'redis1 10.244.28.2 6379'

  - name: redis-slave
    templates:
    - name: redis
      release: redis
    - name: sentinel
      release: redis
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( merge ))
    properties:
      redis:
        master: 10.244.28.2
      sentinel:
        masters:
           - 'redis1 10.244.28.2 6379'

networks: (( merge ))

properties: {}
